version: '3'
services:
  bind:
    build: bind
    image: danieleagle/bind:9.10.3
    container_name: Bind
    restart: always
    ports:
    - '192.168.1.50:53:53/tcp'
    - '192.168.1.50:53:53/udp'
    - '192.168.1.50:10001:10000'
    volumes:
    - './bind/volume_data/main:/data'
    environment:
      - ROOT_PASSWORD=changeMeToSomethingGood
networks:
  default:
    external:
      name: main
