version: '3'
services:
  bind:
    build: bind
    image: danieleagle/bind:9.10.3
    container_name: Bind-NS1
    restart: always
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 10001:10000
    volumes:
    - './bind/volume_data/main:/data'
    environment:
      - ROOT_PASSWORD=changeMeToSomethingGood
networks:
  default:
    external:
      name: main
